### ISSUE TITLE
Is it easy to set this up on ReadTheDocs?

### ISSUE THREAD

**Issue by zsunberg** [bastikr/sphinx-julia#2]
Hi, I'm really excited about the potential to use this with a julia package my team and I are developing. Have you tried to set this up in the ReadTheDocs build environment? (I just started looking at RTD today and am not yet very familiar with their build environment, but it seems like it might be somewhat complex to set it up with julia.)

If readthedocs is not suitable for building docs with this tool, can you give any recommendations for another build service that we could use (i.e. what do you use to build your documentation hosted on github.io?)

Thanks!

**Comment by bastikr** [comment]
Hi,
As far as I can see there is no way to use the autodoc functionality on RTD since it needs a julia interpreter. Using the julia domain defined in sphinx-julia should probably be possible but I haven't tried it.
Setting up gh-pages, which I now use to document my julia projects, is easy enough. The basic principle is described here:
https://daler.github.io/sphinxdoc-test/includeme.html

What's missing in this tutorial is that you need to adapt the clear method in your sphinx make-file since it will otherwise erase files that are needed. For an example look at the make-file of this project. At the moment I always push the documentation by hand but it shouldn't be a problem to do this automatically by either setting up a chron job, using git hooks or github webhooks.

**Comment by zsunberg** [comment]
Thanks! Will try this out soon. I wonder if RTD might eventually make julia part of their default environment...
